print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/spencerstuard/Documents/Games2015/Ball Game/Assets/Models/Skybox.mb"`)
{		
	file -o "/Users/spencerstuard/Documents/Games2015/Ball Game/Assets/Models/Skybox.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/spencerstuard/Documents/Games2015/Ball Game/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/spencerstuard/Documents/Games2015/Ball Game/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/spencerstuard/Documents/Games2015/Ball Game/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
